version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: locationdb
    env_file: .env
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - appnet

  app:
    build: .
    env_file: .env
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - appnet

volumes:
  pgdata:

networks:
  appnet:
